service: lmhd-api
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: /{path}
          method: get
          request:
            parameters:
              paths:
                path: true
  v1:
    handler: bin/v1
    events:
      - http:
          path: /v1/{path}
          method: get
          request:
            parameters:
              paths:
                path: true

plugins:
  - serverless-domain-manager
  - serverless-dotenv-plugin

custom:
  domain:
    dev: api.test.lmhd.me
    prod: api.lmhd.me
  customDomain:
    domainName: ${self:custom.domain.${opt:stage, self:provider.stage}}
    autoDomain: true
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
