service: hello-serverless
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: /{path}
          method: get
          request:
            parameters:
              paths:
                path: true
  v1_name_json:
    handler: bin/v1
    environment:
      OUTPUT_FORMAT: json
      HANDLER: name
    events:
      - http:
          path: v1/name.json
          method: get
  v1_name_hcl:
    handler: bin/v1
    environment:
      OUTPUT_FORMAT: hcl
      HANDLER: name
    events:
      - http:
          path: v1/name
          method: get
      - http:
          path: v1/name.hcl
          method: get
  v1_front_json:
    handler: bin/v1
    environment:
      OUTPUT_FORMAT: json
      HANDLER: front
      PLURALKIT_API_TOKEN: ${env:PLURALKIT_API_TOKEN}
      PLURALKIT_SYSTEM_ID: ${env:PLURALKIT_SYSTEM_ID}
    events:
      - http:
          path: v1/front.json
          method: get
          cors: true
  v1_front_hcl:
    handler: bin/v1
    environment:
      OUTPUT_FORMAT: hcl
      HANDLER: front
      PLURALKIT_API_TOKEN: ${env:PLURALKIT_API_TOKEN}
      PLURALKIT_SYSTEM_ID: ${env:PLURALKIT_SYSTEM_ID}
    events:
      - http:
          path: v1/front
          method: get
      - http:
          path: v1/front.hcl
          method: get

plugins:
  - serverless-domain-manager
  - serverless-dotenv-plugin

custom:
  domain:
    dev: api.test.lmhd.me
    prod: api.lmhd.me
  customDomain:
    domainName: ${self:custom.domain.${opt:stage, self:provider.stage}}
    autoDomain: true
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
