service: hello-serverless
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello_json:
    handler: bin/hello_json
    events:
      - http:
          path: hello.json
          method: get
  hello_hcl:
    handler: bin/hello_hcl
    events:
      - http:
          path: hello.hcl
          method: get
      - http:
          path: hello
          method: get

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.lmhd.me
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
