name: Makefile CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sls_debug:
        description: 'Run serverless in debug mode?'
        default: false
        required: false
        type: boolean

jobs:
  dev:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: Dev
    env:
      PLURALKIT_API_TOKEN: ${{ secrets.PLURALKIT_API_TOKEN }}
      PLURALKIT_SYSTEM_ID: ${{ secrets.PLURALKIT_SYSTEM_ID }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      VAULT_SECRET_SLACK_MEMBERS: ${{ secrets.VAULT_SECRET_SLACK_MEMBERS }}
      VAULT_SECRET_SLACK_TOKENS: ${{ secrets.VAULT_SECRET_SLACK_TOKENS }}
      VAULT_SECRET_SLACK_USER_IDS: ${{ secrets.VAULT_SECRET_SLACK_USER_IDS }}
      AWS_DEFAULT_REGION: us-east-1
      SLS_DEBUG: ${{ github.event.inputs.sls_debug }}

    steps:
    - uses: actions/checkout@v2

    - name: Install AWS CLI
      run: sudo apt-get install awscli
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: '14.15.4' # https://github.com/serverless/serverless/issues/8794#issuecomment-920602821
    - name: Deps
      run: make deps

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: jwt
        path: github_jwt
        role: api-lmhd-me-dev
        secrets: |
            aws/lmhd/prod/creds/api-dev access_key | AWS_ACCESS_KEY_ID ;
            aws/lmhd/prod/creds/api-dev secret_key | AWS_SECRET_ACCESS_KEY ;

    - name: Build
      run: make build

    - name: Deploy to Dev
      run: make deploy-dev

# TODO: get creds for testing
    - name: Test Dev
      run: make test-dev
