name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      
    - name: Deps
      run: make deps
    
    - name: Build
      run: make build
      
      # TODO: get AWS creds (and other secrets) from Vault
    - name: Deploy to Dev
      run: make deploy-dev
      
    - name: Test Dev
      run: make test-dev
