name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: Dev
    env:
      PLURALKIT_API_TOKEN: ${{ secrets.PLURALKIT_API_TOKEN }}
      PLURALKIT_SYSTEM_ID: ${{ secrets.PLURALKIT_SYSTEM_ID }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      VAULT_SECRET_SLACK_MEMBERS: ${{ secrets.VAULT_SECRET_SLACK_MEMBERS }}
      VAULT_SECRET_SLACK_TOKENS: ${{ secrets.VAULT_SECRET_SLACK_TOKENS }}
      VAULT_SECRET_SLACK_USER_IDS: ${{ secrets.VAULT_SECRET_SLACK_USER_IDS }}
      AWS_DEFAULT_REGION: us-east-1
      SLS_DEBUG: true

    steps:
    - uses: actions/checkout@v2

    - name: Install AWS CLI
      run: sudo apt-get install awscli

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: jwt
        path: github_jwt
        role: demo
        secrets: |
            aws/lmhd/prod/creds/test access_key | AWS_ACCESS_KEY_ID ;
            aws/lmhd/prod/creds/test secret_key | AWS_SECRET_ACCESS_KEY ;
            auth/token/lookup-self display_name | TOKEN_DISPLAY_NAME ;
 
# Only un-comment this if you're very confused as to why the AWS creds aren't working
#    - name: Test Env Vars
#      run: env | sort | base64

#    - name: Test AWS Credentials
#      run: aws sts get-caller-identity

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      
    - name: Deps
      run: make deps
    
    - name: Build
      run: make build
      
      # TODO: get AWS creds (and other secrets) from Vault
    - name: Deploy to Dev
      run: make deploy-dev
      
    - name: Test Dev
      run: make test-dev
