name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      PLURALKIT_API_TOKEN: ${{ secrets.PLURALKIT_API_TOKEN }}
      PLURALKIT_SYSTEM_ID: ${{ secrets.PLURALKIT_SYSTEM_ID }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      VAULT_SECRET_SLACK_MEMBERS: ${{ secrets.VAULT_SECRET_SLACK_MEMBERS }}
      VAULT_SECRET_SLACK_TOKENS: ${{ secrets.VAULT_SECRET_SLACK_TOKENS }}
      VAULT_SECRET_SLACK_USER_IDS: ${{ secrets.VAULT_SECRET_SLACK_USER_IDS }}

    steps:
    - uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.3.1
      with:
        url: https://vault.lmhd.me
        method: jwt
        role: dev-api
        secrets: |
            aws/lmhd/prod/creds/test access_key | AWS_ACCESS_KEY_ID ;
            aws/lmhd/prod/creds/test secret_key | AWS_SECRET_ACCESS_KEY

    - name: Test Envs
      run: echo ${VAULT_ADDR}
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      
    - name: Deps
      run: make deps
    
    - name: Build
      run: make build
      
      # TODO: get AWS creds (and other secrets) from Vault
    - name: Deploy to Dev
      run: make deploy-dev
      
    - name: Test Dev
      run: make test-dev
